language: java
jdk:
- oraclejdk8
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
deploy:
  provider: releases
  api_key:
    secure: CutM0kjDHJTXphI0hrMCd9EDJNCAcQjDkP5E6mw4hajE1jFZLq3XNbTiany7s/uSSutXjp9YY5Mgo2D4Pc7UzeiT6O9apa/aQPDJXJ1wrKEzOmiJgTba+unWPhbzsHw03xWG2UI9utYJygjHWmB5qBcy4NM+tts+NUDnCagEOOybo//nhYarLAuBEc6kOjDOdpct+PQtigjgUWZwnuyeCiI/FXsBA0IH/9ebd4ZfydZADEVoV6sKWOMTVoJdL1JM9KzW3OilqZlpBHdlWeyQnql5Izna+ASVwW530Bzo7wfH7Vc3araRhpjxrJ0NiAyRNHvyHXU9uPRJrQEBYSx+GjVeda2smsEFSAP1EaM5a2sQHzq/umrn11IReU+uTxvhbimYchR4jGsJSH51yPUtiR0hyEAmEjEj5AJToPmA0OY0vb1bPOwIamqdUygaA8VZB5kneRSdnUKozOmnCzH1OOttQv1lMm6DqzyrJXM2Uy53LNtE/FbsBYji8a7S1xBP1IrhIOrdPb61jOQC8iDFDOfTvjDlYhDK2chCCGxq2WWPSMGwNZ4wnVYD7LZoh2bIziP9GCqBfVIXJQatJp6JVoMJYtPpNFPfCoUycGQ5vNrqJpd6bmaEMwR+f02NZic3x1XnasmOBt6bkLDUX3VEecSr/tANNw4tKswzPsCTTSg=
  file: build/distributions/easylog-*.zip
  file_glob: true
  skip_cleanup: true
  on:
    tags: true
